StylesPath = ./styles
MinAlertLevel = suggestion

Vocab = LibraryToolsAndResources, PeopleNames, UniversityAndAcademicTerms, LibraryUnitsAndDepartments, PlacesBuildingsAddresses, WritingQualityAndStyleTerms

[*.{md,docx,txt}]
BasedOnStyles = GradeLevel, ReadingEase, WritingQualityStyle




# ---------------------------------------------------------
# Page-Level Checks
# ---------------------------------------------------------

# Readability
# --------------------------------------------------------
ReadingEase.Easy = YES
ReadingEase.Moderate = YES
ReadingEase.Low = YES

# Grade Level
# --------------------------------------------------------
GradeLevel.Academic = YES
GradeLevel.Accessible = YES
GradeLevel.Complex = YES
GradeLevel.Difficult = YES

# Structure
# --------------------------------------------------------
Structure.SentenceLength = YES
Structure.ParagraphLength = YES
