StylesPath = styles
MinAlertLevel = suggestion

[*.{md,docx,txt}]
BasedOnStyles = Library


# ---------------------------------------------------------
# Explicitly Enabled/Disabled Packages
# ---------------------------------------------------------

# Readability:
# --------------------------------------------------------
Library.Readability_Metrics = YES
Library.Readability_Structure = YES
